services:
  fintachartsapi:
    image: ${DOCKER_REGISTRY-}fintachartsapi
    build:
      context: .
      dockerfile: src/Dockerfile
    depends_on:
       - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fintacharts_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SecretPassword0For_FintachartsDB
    ports:
      - "1433:1433"